// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_IMAGES_H
#define PICOPIXEL_LVGL_UI_IMAGES_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifndef EXT_IMG_DESC_T
#define EXT_IMG_DESC_T
typedef struct _ext_img_desc_t {
    const char *name;
    const lv_img_dsc_t *img_dsc;
} ext_img_desc_t;
#endif

// Original PicoPixel image
extern const lv_img_dsc_t hpb3vuwbytl44uh;

// Weather icons
extern const lv_img_dsc_t weather_100;   // 晴
extern const lv_img_dsc_t weather_101;   // 多云
extern const lv_img_dsc_t weather_102;   // 少云
extern const lv_img_dsc_t weather_103;   // 晴间多云
extern const lv_img_dsc_t weather_104;   // 阴
extern const lv_img_dsc_t weather_300;   // 阵雨
extern const lv_img_dsc_t weather_302;   // 雷阵雨
extern const lv_img_dsc_t weather_305;   // 小雨
extern const lv_img_dsc_t weather_306;   // 中雨
extern const lv_img_dsc_t weather_307;   // 大雨
extern const lv_img_dsc_t weather_400;   // 小雪
extern const lv_img_dsc_t weather_401;   // 中雪
extern const lv_img_dsc_t weather_402;   // 大雪
extern const lv_img_dsc_t weather_404;   // 雨夹雪
extern const lv_img_dsc_t weather_501;   // 雾
extern const lv_img_dsc_t weather_511;   // 霾

extern const ext_img_desc_t images[];


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_IMAGES_H*/
