// Generated by PicoPixel.io — https://picopixel.io
#include "images.h"

// Original PicoPixel image
#include "images/hpb3vuwbytl44uh.c"

// Weather icons
#include "images/weather_100.c"
#include "images/weather_101.c"
#include "images/weather_102.c"
#include "images/weather_103.c"
#include "images/weather_104.c"
#include "images/weather_300.c"
#include "images/weather_302.c"
#include "images/weather_305.c"
#include "images/weather_306.c"
#include "images/weather_307.c"
#include "images/weather_400.c"
#include "images/weather_401.c"
#include "images/weather_402.c"
#include "images/weather_404.c"
#include "images/weather_501.c"
#include "images/weather_511.c"

const ext_img_desc_t images[] = {
    { "hpb3vuwbytl44uh", &hpb3vuwbytl44uh },
    { "weather_100", &weather_100 },
    { "weather_101", &weather_101 },
    { "weather_102", &weather_102 },
    { "weather_103", &weather_103 },
    { "weather_104", &weather_104 },
    { "weather_300", &weather_300 },
    { "weather_302", &weather_302 },
    { "weather_305", &weather_305 },
    { "weather_306", &weather_306 },
    { "weather_307", &weather_307 },
    { "weather_400", &weather_400 },
    { "weather_401", &weather_401 },
    { "weather_402", &weather_402 },
    { "weather_404", &weather_404 },
    { "weather_501", &weather_501 },
    { "weather_511", &weather_511 },
    { NULL, NULL }  // Sentinel
};
