// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_SCREENS_H
#define PICOPIXEL_LVGL_UI_SCREENS_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _objects_t {
    lv_obj_t *badge_main;
    lv_obj_t *badge_success;
    lv_obj_t *badge_loading;
    lv_obj_t *badge_config;
    lv_obj_t *container_3;
    lv_obj_t *qweather_icons;
    lv_obj_t *label_6;
    lv_obj_t *container_2;
    lv_obj_t *container_1;
    lv_obj_t *label_date;
    lv_obj_t *label_4;
    lv_obj_t *label_1;
    lv_obj_t *arc_3;
    lv_obj_t *label_update;
    lv_obj_t *label_3;
    lv_obj_t *image_1;
    lv_obj_t *label_detail;
    lv_obj_t *arc_1;
    lv_obj_t *container_4;
    lv_obj_t *label_time;
    lv_obj_t *label_7;
    lv_obj_t *label_temp;
    lv_obj_t *arc_2;
    lv_obj_t *label_2;
    lv_obj_t *label_5;
    lv_obj_t *label_weather;
} objects_t;

extern objects_t objects;

enum ScreensEnum {
    SCREEN_ID_BADGE_MAIN = 1,
    SCREEN_ID_BADGE_SUCCESS = 2,
    SCREEN_ID_BADGE_LOADING = 3,
    SCREEN_ID_BADGE_CONFIG = 4,
};

void create_screen_badge_main();
void tick_screen_badge_main();
void delete_screen_badge_main();
void create_screen_badge_success();
void tick_screen_badge_success();
void delete_screen_badge_success();
void create_screen_badge_loading();
void tick_screen_badge_loading();
void delete_screen_badge_loading();
void create_screen_badge_config();
void tick_screen_badge_config();
void delete_screen_badge_config();

void tick_screen_by_id(enum ScreensEnum screenId);
void tick_screen(int screen_index);

void delete_screen_by_id(enum ScreensEnum screenId);

void create_screens();


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_SCREENS_H*/
