// Generated by PicoPixel.io — https://picopixel.io
#include <string.h>

#include "screens.h"
#include "images.h"
#include "fonts/fonts.h"
#include "actions.h"
#include "vars.h"
#include "styles.h"
#include "ui.h"

objects_t objects;
lv_obj_t *tick_value_change_obj;
uint32_t active_theme_index = 0;

void create_screen_badge_main() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.badge_main = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 240, 240);
    {
        lv_obj_t *parent_obj = obj;
        {
            // container_4
            lv_obj_t *obj = lv_obj_create(parent_obj);
            objects.container_4 = obj;
            lv_obj_set_pos(obj, 0, 0);
            lv_obj_set_size(obj, 240, 240);
            lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // qweather_icons — 48x48, centered horizontally
                    // PNG icon will be loaded from SPIFFS at runtime
                    lv_obj_t *obj = lv_img_create(parent_obj);
                    objects.qweather_icons = obj;
                    lv_obj_set_pos(obj, 96, 80);
                    lv_obj_set_size(obj, 48, 48);
                }
                {
                    // label_date
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.label_date = obj;
                    // 水平居中：x=0, width=240, 文字居中对齐
                    lv_obj_set_pos(obj, 0, 51);
                    lv_obj_set_size(obj, 240, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_align(obj, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
                    // 保持空文本, 真实日期由 display_main_screen() 填充
                    // 避免上电瞬间显示 PicoPixel 原始占位值 "2025-01-15"
                    lv_label_set_text(obj, "");
                }
                {
                    // label_update
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.label_update = obj;
                    lv_obj_set_pos(obj, 0, 184);
                    lv_obj_set_size(obj, 240, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_align(obj, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
                    // 保持空文本, 真实更新时间由 display_main_screen() 填充
                    lv_label_set_text(obj, "");
                }
                {
                    // label_detail
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.label_detail = obj;
                    lv_obj_set_pos(obj, 58, 160);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    // 保持空文本, 真实湿度/风速由 display_main_screen() 填充
                    lv_label_set_text(obj, "");
                }
                {
                    // label_time
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.label_time = obj;
                    // 水平居中：x=0, width=240, 文字居中对齐
                    lv_obj_set_pos(obj, 0, 25);
                    lv_obj_set_size(obj, 240, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_align(obj, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_transform_pivot_x(obj, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_transform_pivot_y(obj, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_transform_angle(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    // 保持空文本, 真实时间由 display_main_screen() 填充
                    // 避免上电瞬间显示 PicoPixel 原始占位值 "9:00"
                    lv_label_set_text(obj, "");
                }
                {
                    // label_temp — 右半边水平居中 (x=120~240)
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.label_temp = obj;
                    lv_obj_set_pos(obj, 120, 136);
                    lv_obj_set_size(obj, 120, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_align(obj, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
                    // 保持空文本, 真实温度由 display_main_screen() 填充
                    lv_label_set_text(obj, "");
                }
                {
                    // label_weather — 左半边水平居中 (x=0~120)
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.label_weather = obj;
                    lv_obj_set_pos(obj, 0, 134);
                    lv_obj_set_size(obj, 120, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_align(obj, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
                    // 保持空文本, 真实天气描述由 display_main_screen() 填充
                    lv_label_set_text(obj, "");
                }
            }
        }
    }

    tick_screen_badge_main();
}

void tick_screen_badge_main() {
}


void create_screen_badge_success() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.badge_success = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 240, 240);
    {
        lv_obj_t *parent_obj = obj;
        {
            // container_2
            lv_obj_t *obj = lv_obj_create(parent_obj);
            objects.container_2 = obj;
            lv_obj_set_pos(obj, 4, 4);
            lv_obj_set_size(obj, 232, 232);
            lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // label_3
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.label_3 = obj;
                    lv_obj_set_pos(obj, 68, 151);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Press any key");
                }
                {
                    // arc_2
                    lv_obj_t *obj = lv_arc_create(parent_obj);
                    objects.arc_2 = obj;
                    lv_obj_set_pos(obj, 28, 28);
                    lv_obj_set_size(obj, 176, 176);
                    lv_arc_set_bg_angles(obj, 0, 359);
                    lv_arc_set_range(obj, 0, 359);
                    lv_arc_set_value(obj, 359);
                    lv_obj_set_style_arc_opa(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_rounded(obj, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_color(obj, lv_color_hex(0x4924), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_rounded(obj, true, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_color(obj, lv_color_hex(0xe73a), LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_bg_opa(obj, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_width(obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_width(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                }
                {
                    // label_2
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.label_2 = obj;
                    lv_obj_set_pos(obj, 87, 108);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, LV_FONT_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Success");
                }
            }
        }
    }

    tick_screen_badge_success();
}

void tick_screen_badge_success() {
}


void create_screen_badge_loading() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.badge_loading = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 240, 240);
    {
        lv_obj_t *parent_obj = obj;
        {
            // container_1
            lv_obj_t *obj = lv_obj_create(parent_obj);
            objects.container_1 = obj;
            lv_obj_set_pos(obj, 4, 4);
            lv_obj_set_size(obj, 233, 232);
            lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // label_1 — 屏幕正中央（水平 & 垂直居中）
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.label_1 = obj;
                    lv_obj_set_pos(obj, 0, 108);
                    lv_obj_set_size(obj, 233, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_align(obj, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, LV_FONT_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Syscing...");
                }
                {
                    // arc_1
                    lv_obj_t *obj = lv_arc_create(parent_obj);
                    objects.arc_1 = obj;
                    lv_obj_set_pos(obj, 28, 28);
                    lv_obj_set_size(obj, 176, 176);
                    lv_arc_set_bg_angles(obj, 0, 359);
                    lv_arc_set_range(obj, 0, 359);
                    lv_arc_set_value(obj, 359);
                    lv_obj_set_style_arc_opa(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_rounded(obj, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_color(obj, lv_color_hex(0x4924), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_rounded(obj, true, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_color(obj, lv_color_hex(0xe73a), LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_bg_opa(obj, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_width(obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_width(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                }
            }
        }
    }

    tick_screen_badge_loading();
}

void tick_screen_badge_loading() {
}


void create_screen_badge_config() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.badge_config = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 240, 240);
    {
        lv_obj_t *parent_obj = obj;
        {
            // container_3
            lv_obj_t *obj = lv_obj_create(parent_obj);
            objects.container_3 = obj;
            lv_obj_set_pos(obj, 0, 0);
            lv_obj_set_size(obj, 240, 240);
            lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // label_6
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.label_6 = obj;
                    lv_obj_set_pos(obj, -1, 112);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_transform_pivot_x(obj, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0x8c10), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_transform_pivot_y(obj, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_transform_angle(obj, -900, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_align(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Wechat");
                }
                {
                    // label_4
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.label_4 = obj;
                    lv_obj_set_pos(obj, 73, 189);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0x8c10), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Config Mode");
                }
                {
                    // arc_3
                    lv_obj_t *obj = lv_arc_create(parent_obj);
                    objects.arc_3 = obj;
                    lv_obj_set_pos(obj, 0, 3);
                    lv_obj_set_size(obj, 235, 234);
                    lv_arc_set_bg_angles(obj, 0, 359);
                    lv_arc_set_range(obj, 0, 359);
                    lv_arc_set_value(obj, 359);
                    lv_obj_set_style_arc_opa(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_rounded(obj, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_color(obj, lv_color_hex(0x4924), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_rounded(obj, true, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_color(obj, lv_color_hex(0xe73a), LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_bg_opa(obj, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_width(obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_width(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_arc_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                }
                {
                    // image_1
                    lv_obj_t *obj = lv_img_create(parent_obj);
                    objects.image_1 = obj;
                    lv_obj_set_pos(obj, 56, 56);
                    lv_obj_set_size(obj, 128, 128);
                    lv_img_set_src(obj, &hpb3vuwbytl44uh);
                    lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
                    lv_img_set_zoom(obj, 82);
                }
                {
                    // label_7
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.label_7 = obj;
                    lv_obj_set_pos(obj, 185, 112);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_transform_pivot_x(obj, 17, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_transform_pivot_y(obj, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_transform_angle(obj, -900, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Scan");
                }
                {
                    // label_5
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.label_5 = obj;
                    lv_obj_set_pos(obj, 128, 32);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0x8c10), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Wake");
                }
            }
        }
    }

    tick_screen_badge_config();
}

void tick_screen_badge_config() {
}



typedef void (*tick_screen_func_t)();
tick_screen_func_t tick_screen_funcs[] = {
    tick_screen_badge_main,
    tick_screen_badge_success,
    tick_screen_badge_loading,
    tick_screen_badge_config,
};
void tick_screen(int screen_index) {
    tick_screen_funcs[screen_index]();
}
void tick_screen_by_id(enum ScreensEnum screenId) {
    tick_screen_funcs[screenId - 1]();
}

void delete_screen_badge_main() {
    if (objects.badge_main != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.badge_main);
        lv_obj_del(objects.badge_main);
    }
    objects.badge_main = 0;
    objects.container_4 = 0;
    objects.qweather_icons = 0;
    objects.label_date = 0;
    objects.label_update = 0;
    objects.label_detail = 0;
    objects.label_time = 0;
    objects.label_temp = 0;
    objects.label_weather = 0;
}

void delete_screen_badge_success() {
    if (objects.badge_success != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.badge_success);
        lv_obj_del(objects.badge_success);
    }
    objects.badge_success = 0;
    objects.container_2 = 0;
    objects.label_3 = 0;
    objects.arc_2 = 0;
    objects.label_2 = 0;
}

void delete_screen_badge_loading() {
    if (objects.badge_loading != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.badge_loading);
        lv_obj_del(objects.badge_loading);
    }
    objects.badge_loading = 0;
    objects.container_1 = 0;
    objects.label_1 = 0;
    objects.arc_1 = 0;
}

void delete_screen_badge_config() {
    if (objects.badge_config != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.badge_config);
        lv_obj_del(objects.badge_config);
    }
    objects.badge_config = 0;
    objects.container_3 = 0;
    objects.label_6 = 0;
    objects.label_4 = 0;
    objects.arc_3 = 0;
    objects.image_1 = 0;
    objects.label_7 = 0;
    objects.label_5 = 0;
}


typedef void (*delete_screen_func_t)();
delete_screen_func_t delete_screen_funcs[] = {
    delete_screen_badge_main,
    delete_screen_badge_success,
    delete_screen_badge_loading,
    delete_screen_badge_config,
};
void delete_screen_by_id(enum ScreensEnum screenId) {
    delete_screen_funcs[screenId - 1]();
}

void create_screens() {
    lv_disp_t *dispp = lv_disp_get_default();
    // Use dark theme (true) to match the editor's appearance - white text on dark buttons
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    create_screen_badge_main();
    create_screen_badge_success();
    create_screen_badge_loading();
    create_screen_badge_config();
}
