// Generated by PicoPixel.io — https://picopixel.io
#include "ui.h"
#include "screens.h"
#include "images.h"
#include "actions.h"
#include "vars.h"

#include <string.h>

static int16_t currentScreen = -1;

static lv_obj_t *getLvglObjectFromIndex(int32_t index) {
    if (index == -1) {
        return 0;
    }
    return ((lv_obj_t **)&objects)[index];
}

void loadScreen(enum ScreensEnum screenId) {
    currentScreen = screenId - 1;
    lv_obj_t *screen = getLvglObjectFromIndex(currentScreen);
    lv_scr_load_anim(screen, LV_SCR_LOAD_ANIM_FADE_IN, 200, 0, false);
}

void ui_init() {
    // 只创建 LVGL 屏幕对象, 不立即加载到显示设备.
    // 所有 label 默认文本都是空字符串 (见 screens.c create_screen_badge_main).
    // 由 display_main_screen() 先写入真实时间/天气数据, 再第一次调用 loadScreen()
    // 把屏幕推到显示 — 这样上电就不会出现 PicoPixel 原始占位值 (9:00 / 2025-01-15).
    create_screens();
    currentScreen = -1;
}

void ui_tick() {
    tick_screen(currentScreen);
}
